//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoClub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_1942 {
            get {
                object obj = ResourceManager.GetObject("feat-1942", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_adventure_island {
            get {
                object obj = ResourceManager.GetObject("feat-adventure-island", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_adventure_island_2 {
            get {
                object obj = ResourceManager.GetObject("feat-adventure-island-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_balloon_fight {
            get {
                object obj = ResourceManager.GetObject("feat-balloon-fight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_battle_tank {
            get {
                object obj = ResourceManager.GetObject("feat-battle-tank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_battletoads {
            get {
                object obj = ResourceManager.GetObject("feat-battletoads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_bomberman {
            get {
                object obj = ResourceManager.GetObject("feat-bomberman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_city_connection {
            get {
                object obj = ResourceManager.GetObject("feat-city-connection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_contra {
            get {
                object obj = ResourceManager.GetObject("feat-contra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_donkey_kong {
            get {
                object obj = ResourceManager.GetObject("feat-donkey-kong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_double_dragon {
            get {
                object obj = ResourceManager.GetObject("feat-double-dragon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_excitebike {
            get {
                object obj = ResourceManager.GetObject("feat-excitebike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_final_fantasy {
            get {
                object obj = ResourceManager.GetObject("feat-final-fantasy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_galaga {
            get {
                object obj = ResourceManager.GetObject("feat-galaga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_ice_climber {
            get {
                object obj = ResourceManager.GetObject("feat-ice-climber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_jeopardy_ {
            get {
                object obj = ResourceManager.GetObject("feat-jeopardy!", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_kung_fu {
            get {
                object obj = ResourceManager.GetObject("feat-kung-fu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_lode_runner {
            get {
                object obj = ResourceManager.GetObject("feat-lode-runner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_metal_gear {
            get {
                object obj = ResourceManager.GetObject("feat-metal-gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_metroid {
            get {
                object obj = ResourceManager.GetObject("feat-metroid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_pac_man {
            get {
                object obj = ResourceManager.GetObject("feat-pac-man", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_paperboy {
            get {
                object obj = ResourceManager.GetObject("feat-paperboy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_pinball {
            get {
                object obj = ResourceManager.GetObject("feat-pinball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_popeye {
            get {
                object obj = ResourceManager.GetObject("feat-popeye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_rambo {
            get {
                object obj = ResourceManager.GetObject("feat-rambo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_soccer {
            get {
                object obj = ResourceManager.GetObject("feat-soccer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_super_mario_bros_ {
            get {
                object obj = ResourceManager.GetObject("feat-super-mario-bros.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_super_mario_bros__3 {
            get {
                object obj = ResourceManager.GetObject("feat-super-mario-bros.-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_teenage_mutant_ninja_turtles {
            get {
                object obj = ResourceManager.GetObject("feat-teenage-mutant-ninja-turtles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_tetris {
            get {
                object obj = ResourceManager.GetObject("feat-tetris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_the_simpsons__bart_vs__the_space_mutants {
            get {
                object obj = ResourceManager.GetObject("feat-the-simpsons.-bart-vs.-the-space-mutants", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_ultima__exodus {
            get {
                object obj = ResourceManager.GetObject("feat-ultima.-exodus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_wild_gunman {
            get {
                object obj = ResourceManager.GetObject("feat-wild-gunman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feat_zelda_2__the_adventure_of_link {
            get {
                object obj = ResourceManager.GetObject("feat-zelda-2.-the-adventure-of-link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1942,Adventure Island,Adventure Island 2,Balloon Fight,Battle Tank,Battletoads,Bomberman,City Connection,Contra,Donkey Kong,Double Dragon,Excitebike,Final Fantasy,Galaga,Ice Climber,Jeopardy!,Kung Fu,Lode Runner,Metal Gear,Metroid,Pac-Man,Paperboy,Pinball,Popeye,Rambo,The Simpsons. Bart vs. the Space Mutants,Soccer,Super Mario Bros.,Super Mario Bros. 3,Teenage Mutant Ninja Turtles,Tetris,Ultima. Exodus,Wild Gunman,Zelda 2: The Adventure of Link.
        /// </summary>
        internal static string titulos_nintendo {
            get {
                return ResourceManager.GetString("titulos_nintendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal Gear Solid,
        ///Gran Turismo 2,
        ///Castlevania: Symphony of the Night,
        ///Final Fantasy IX,
        ///Silent Hill,
        ///Final Fantasy VIII,
        ///Syphon Filter,
        ///Suikoden 2,
        ///ISS PRO Evolution 2 ,
        ///Grandia,
        ///Tony Hawk&apos;s Pro Skater 2,
        ///Dino Crisis 2 ,
        ///ISS Pro Evolution,
        ///Xenogears,
        ///Resident Evil 3: Nemesis,
        ///Medal of Honor ,
        ///Street Fighter Alpha 3,
        ///Toca World Touring Carsm
        ///OddWorld: Abe&apos;s Oddyse,
        ///Ridge Racer Type 4 ,
        ///Tony Hawk&apos;s Pro Skater ,
        ///WWF SmackDown 2,
        ///Driver,
        ///Medal of Honor Underground,
        ///R-Type Delta,
        ///Spiderm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string titulos_playstation {
            get {
                return ResourceManager.GetString("titulos_playstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spider-Man and Venom: Maximum Carnage,
        ///Road Rash 2,
        ///Tiny Toon Adventures: Buster&apos;s Hidden Treasure,
        ///Shadow Dancer: The Secret of Shinobi,
        ///Michael Jackson&apos;s Moonwalker,
        ///Cool Spot,
        ///Shining Force II,
        ///Contra: Hard Corps,
        ///Toejam &amp; Earl,
        ///Ultimate Mortal Kombat 3,
        ///Vectorman,
        ///Castlevania: Bloodlines,
        ///Golden Axe,
        ///Castle of Illusion Starring Mickey Mouse,
        ///Batman: The Video Game,
        ///hostbusters,
        ///Altered Beast,
        ///Tecmo Cup Football Game,
        ///Battletoads,
        ///Ren &amp; Stimpy: Stimpy&apos;s Invention,
        ///Toy Story,
        ///Turtles  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string titulos_sega {
            get {
                return ResourceManager.GetString("titulos_sega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_95_spin_disc_icon {
            get {
                object obj = ResourceManager.GetObject("windows-95-spin-disc-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
